### ISSUE TITLE
Hosting with Amplify

### ISSUE THREAD

**Issue by mindsetgareth** [beamsies/gatsby-starter-auth-aws-amplify#8]
Im having issues hosting this on Amplify, an XML error appears with AccessDenied.

Has anyone came across this issue?

It works perfectly locally.

**Comment by beamsies** [comment]
You're hosting the site itself on AWS with Amplify?

Can you please share the entire error?

It sounds there's a permissions issue with the IAM config of the app, take a look at that.

**Comment by mindsetgareth** [comment]
yes hosting the site on AWS with Amplify.

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>1F727FF5C79DC704</RequestId>
<HostId>
i3g8VGrC/ldMGjNHyBhChGtu9smgo5N344/2W13bo3/gkr0toDf8V880NSj5kWw9oLE6f2w5stQ=
</HostId>
</Error>

I shall have a look there, thanks. I also tried playing with the redirects with no luck either.

**Comment by andrewphahn** [comment]
Facing the same issue. It seems to be because there is no index.html generated at the root. Trying to figure out how to change the project to create it, but new to this stack...

**Comment by beamsies** [comment]
@mindsetgareth  and @andrewphahn 

Take a look at this discussion:
https://github.com/aws-amplify/amplify-console/issues/436#issuecomment-629872652

It seems people were having a similar issue and it was fixed with a rewrite/redirect.

**Comment by andrewphahn** [comment]
> @mindsetgareth and @andrewphahn
> 
> Take a look at this discussion:
> [aws-amplify/amplify-console#436 (comment)](https://github.com/aws-amplify/amplify-console/issues/436#issuecomment-629872652)
> 
> It seems people were having a similar issue and it was fixed with a rewrite/redirect.

Yes, a rewrite handles direct access to the app/routes... if there is an /index.html to route to. Reading the client side routing docs and understanding what `gatsby-node.js` is doing helped me find the solution.

<img width="1064" alt="Screen Shot 2020-08-04 at 10 06 36 PM" src="https://user-images.githubusercontent.com/1181716/89370905-15140880-d69f-11ea-8fb7-65acd650d322.png">

So any resource that results in a 404 will return the contents of `app/index.html` that is generated by the build.

Thanks for the pointer @beamsies

**Comment by beamsies** [comment]
Closing as this seems to not be an issue with this repo but with an issue with AWS Amplify Hosting configuration.

**Comment by mindsetgareth** [comment]
@andrewphahn and @beamsies Thanks very much got it working.
